[project]
name = "reel-liseer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "HamzaSyrage", email = "hamzasyrage@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "imageio-ffmpeg>=0.6.0",
    "python-dotenv>=1.2.3",
    "python-telegram-bot>=22.8",
    "uvicorn>=0.53.0",
    "yt-dlp>=2026.8.19",
]

[project.scripts]
reel-liseer = "reel_liseer:main"

[tool.fastapi]
entrypoint = "src.reel_liseer.webapp:app"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
